services:
  postgres:
    image: postgres:14
    container_name: fahasa_postgres
    environment:
      POSTGRES_USER: fahasa
      POSTGRES_PASSWORD: fahasa123
      POSTGRES_DB: fahasa_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fahasa_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fahasa -d fahasa_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Crawler
  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    container_name: crawler
    volumes:
      - ./data:/app/data
      - ./crawler:/app/crawler
    ports:
      - "8003:8000"
    environment:
      - CRAWLER_CONFIG_PATH=/app/crawler/config/crawler_config.json
      - CRAWLER_SOURCE_ID=fahasa
      - INGESTION_CALLBACK_URL=http://ingestion:8000/trigger
    networks:
      - fahasa_network
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s = socket.socket(); s.connect(('localhost', 8000))\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["python", "-m", "crawler.api"]

  # API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fahasa_api
    ports:
      - "8001:8000"
    networks:
      - fahasa_network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=fahasa_db
      - DB_USER=fahasa
      - DB_PASS=fahasa123
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; s = socket.socket(); s.connect(('localhost', 8000))\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Ingestion
  ingestion:
    build:
      context: .
      dockerfile: Dockerfile.ingestion
    container_name: ingestion
    volumes:
      - ./data:/app/data
      - ./ingestion:/app/ingestion
    ports:
      - "8004:8000"
    networks:
      - fahasa_network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=fahasa_db
      - DB_USER=fahasa
      - DB_PASS=fahasa123
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_healthy
    restart: on-failure
    command: ["uvicorn", "ingestion.api:app", "--host", "0.0.0.0", "--port", "8000"]

  # Nginx
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fahasa_network
    depends_on:
      api:
        condition: service_healthy
    restart: on-failure

networks:
  fahasa_network:
    driver: bridge

volumes:
  postgres_data: 