FROM python:3.9-slim

WORKDIR /app

COPY crawler/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY crawler/ ./crawler/

# Tat tao file .pyc va thu muc __pycache__
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

CMD ["python", "-m", "crawler.main"] 