FROM python:3.9-slim

WORKDIR /app

# Cài đặt các dependencies
COPY web/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy toàn bộ code web vào container
COPY web/ ./web/

# Thiết lập biến môi trường
ENV FLASK_APP=app.py
ENV FLASK_ENV=production
ENV PYTHONPATH=/app

# Set environment variables
ENV PYTHONUNBUFFERED=1
# Tat tao file .pyc va thu muc __pycache__
ENV PYTHONDONTWRITEBYTECODE=1

# Expose port 8000 cho Flask app
EXPOSE 8000

# Chạy ứng dụng
CMD ["python", "app.py"] 