FROM python:3.9-slim

WORKDIR /app

# Install PostgreSQL dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc \
    python3-dev \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY ingestion/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ingestion/ .

# Set environment variables
ENV PYTHONUNBUFFERED=1

CMD ["python", "ingestion.py"] 